name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/runletapp/docker/daemon:latest
    - name: Login to registry
      run: docker login docker.pkg.github.com --username runletapp -p ${{ secrets.registry_password }}
    - name: Push
      run: docker.pkg.github.com/runletapp/docker/daemon:latest
